### ISSUE TITLE
Camera Zooms out to the exterior of VAB

### ISSUE THREAD

**Issue by Wetmelon** [NathanKell/RealSolarSystem#48]
The camera sometimes zooms out to the exterior of the VAB and must be zoomed back in (rather slowly) before I can see what I'm building.

I believe it only happens when there is a rocket "loaded" in the VAB already and I select "Revert to Vehicle Assembly Building".

It may only occur when the rocket is sufficiently tall, though I have not tested this specifically.

**Comment by NathanKell** [comment]
Thanks for putting this where I might remember. The easy solution is to disable RSS's camera / sizing changes and just use snjo's Hangar Extender.

**Comment by pjf** [comment]
Woah, this is caused by RSS? I had no idea. Thank you! :)

**Comment by NathanKell** [comment]
Functionality removed in RSS, now done by Hangar Extender.
