### ISSUE TITLE
CKAN forces installation of RealismOverhaul while installing RSS

### ISSUE THREAD

**Issue by Fleskhjerta14577** [NathanKell/RealSolarSystem#49]
@NathanKell

Don't know if this is a bug or intended, but it's a bit annoying and I can't uninstall RO without removing RSS at the same time.

Should I post this in the CKAN issues page? There's other things that have the same problem.

**Comment by NathanKell** [comment]
I am unaware of any reason CKAN would _require_ you to install RO with RSS. RSS may recommend RO--that is, it may default to being installed--but it certainly doesn't require it. @Dazpoet ?

**Comment by Dazpoet** [comment]
I'm unable to reproduce this behaviour on my testinstall of 0.90, which I assume is the KSP version used here? This is with the latest versions of RO and RSS in CKAN for 0.90.

RealismOverhaul does depend on RSS but that doesn't force the removal of both upon removing RO.
RSS also recommends RealismOverhaul but again that doesn't mean uninstalling one forces the uninstall of the other.

I need more information such as CKAN client version, installed versions of RO and RSS, KSP version, output of 'ckan list --porcelain' and preferably the registry.json file from your CKAN folder in the KSP root directory.

**Comment by Dazpoet** [comment]
Oh and a picture of the changeset along with the list of mods you've chosen for removal would also help me narrow this down a bit :)

**Comment by Fleskhjerta14577** [comment]
Okay, I think I figured it out. I actually didn't check this in a while, but it's probably just a problem on my end. I just went to do that again, and updated CKAN before I did. It worked this time, no idea why. Maybe it was just a one time bug. Thanks.
