### ISSUE TITLE
Propellant stability when staging/throttling up.

### ISSUE THREAD

**Issue by kiwivogel** [NathanKell/RealSolarSystem#51]
Hello, not so much an issue as a suggestion. Now that squad has put a UI framework for showing us when it's safe to stage our parachutes would it be possible to put something similar in place for engine propellant stability? That would be seriously helpful. (I have no idea if squad uses assets for changing the colour of the parachute icon of if it's a simple palet change but it seems this would be easy to implement.) Thanks!

**Comment by NathanKell** [comment]
Ooh, that's a neat idea!
You should post that issue on [the RealFuels repository](https://github.com/NathanKell/ModularFuelSystem/) though, this is the one for RealSolarSystem :P
