### ISSUE TITLE
{RQ} Asteroid belt

### ISSUE THREAD

**Issue by KAmaia** [NathanKell/RealSolarSystem#61]
Could we please have a legit asteroid belt?  As in more than just the one or two lone stragglers?

**Comment by jbengtson** [comment]
You might want to make sure you're on the correct repo for a request, the last commit to this one was in 2015. Here is the correct repo: 

https://github.com/KSP-RO/RealSolarSystem

Also ensure you are using files from the latest repo, that being the Kopernicus version of Real Solar System on 1.2.2, before making such a request. Thank you.
