### ISSUE TITLE
Update to KSP 1.3

### ISSUE THREAD

**Issue by Clement-Cardot** [NathanKell/RealSolarSystem#62]
Hello can you update the files for the new version of KSP because I love your Mod :) 
Congratulation for your work 🥇 
keep on this way ;)

**Comment by jbengtson** [comment]
You might want to make sure you're on the correct repo for a request, the last commit to this one was in 2015. Here is the correct repo: 

https://github.com/KSP-RO/RealSolarSystem

Also ensure you are using files from the latest repo, that being the Kopernicus version of Real Solar System on 1.2.2, before making such a request. Thank you.
